### PR TITLE
Retire alchemy

### PR DESCRIPTION
**Pull request by Lnaden**
Deprecate this repository by marking it in the README.

Downgrade deprecated section heads
Remove "status" badges (keep Zenodo for documentation)
Will remove travis-ci integration as service if approved

### CODE REVIEW

**Review by andrrizzi — APPROVED** [review]
LGTM

**Review by jchodera — COMMENTED** [review]
How about we
* Move the old `README.md` to `README-DEPRECATED.md` unchanged
* Replace `README.md` with the deprecation notice (rather than the contents of the original README) and a pointer to [the new `openmmtools.alchemy` docs](http://openmmtools.readthedocs.io/en/latest/alchemy.html) and the [`openmmtools` repo](https://github.com/choderalab/openmmtools)

**Comment by Lnaden** [comment]
@jchodera sounds good to me. I'll make the changes, merge this pr, and remove the travis tests from the repo.

**Comment by jchodera** [comment]
No need to muck with Travis since I've just disabled night.es

**Pull request merged**
