### PR TITLE
Test direct and reciprocal space energies

### PR DESCRIPTION
**Pull request by andrrizzi**
This augment `check_interacting_energy()` to test that we model correctly the direct space energy in `PME` and `Ewald` methods. The test is marked `slow` but it passes locally, so if all other tests work this should be ready for review/merging.

### CODE REVIEW

**Comment by jchodera** [comment]
Can you explain a bit more how it works? Does it test the energy agreement directly, or just the overlap? How does it handle the reciprocal-space exceptions that are computed in the direct-space component of `PME`?

**Comment by andrrizzi** [comment]
Sure! Sorry, if the diff is messy, I changed few variable names to be consistent with the code. With respect to the old test, for Ewald and PME now we:
- separate direct space and indirect space energy by using `nonbonded_force.setReciprocalSpaceForceGroup()`
- compute the correction that OpenMM adds to the direct space caused by the contribution of exceptions/exclusions in the reciprocal space energy.
- check that both the direct and reciprocal space energies of the original `NonbondedForce` and the `unmodified NonbondedForce` for nonalchemical-nonalchemical interactions are the same.
- check that the direct space energy (reciprocal space energy for alchemical atoms is still untested) for alchemical-alchemical and alchemical-nonalchemical is the same in the the original `NonbondedForce` and the `CustomNonbondedForce`s up to the OpenMM correction that we computed before.

**Comment by jchodera** [comment]
> compute the correction that OpenMM adds to the direct space caused by the contribution of exceptions/exclusions in the reciprocal space energy.

Cool! Do you get an idea for how large this correction is?

I just posted an issue to `alchemy` reminding us that we can improve overlap if we add this term in:
https://github.com/choderalab/alchemy/issues/48

Maybe we should actually add now while we know how to tackle the correction?

**Comment by andrrizzi** [comment]
> Cool! Do you get an idea for how large this correction is?

It's big. For host-guest system, the correction for the ligand atoms only is about 280kJ/mol.

> Maybe we should actually add now while we know how to tackle the correction?

I'll answer on that thread.

**Comment by jchodera** [comment]
Is this ready to merge, @andrrizzi ?

**Comment by andrrizzi** [comment]
Yes!

**Pull request merged**
