### PR TITLE
[WIP] Add py3 support

### PR DESCRIPTION
**Pull request by jchodera**
Starting with the addition of py3 travis testing

### CODE REVIEW

**Comment by jchodera** [comment]
Anyone know what might be going on [here](https://travis-ci.org/choderalab/alchemy/jobs/88838483#L652-L709) with python3 issues?

@andrrizzi? @bas-rustenburg?

**Comment by andrrizzi** [comment]
Could it be that the import should be done as

``` python
from alchemy.alchemy import AlchemicalState
```

instead of

``` python
from alchemy import AlchemicalState
```

?

**Comment by jchodera** [comment]
Could be!  I had thought the `__init__.py`'s `from alchemy import *` would import `AlchemicalState` into the appropriate namespace, but maybe I am wrong!

**Comment by andrrizzi** [comment]
Oh, I didn't check what was inside **init**.py . Still I wouldn't be surprised if the global package name shadowed the imported module. Also, I think something changed in the import mechanism since python33. I'll try to run these tests on my machine.

**Comment by jchodera** [comment]
You're totally right!
http://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

**Comment by jchodera** [comment]
Failing now because there is no `openmm-dev` package for py3.5.  I've updated Jenkins to add 3.5 and am rebuilding now.

**Comment by jchodera** [comment]
This is now only failing due to test timeouts (py27 and py34) and lack of pymbar built for py35.

**Comment by jchodera** [comment]
Tests pass locally, but just time out on travis.

**Pull request merged**
